### PR TITLE
Fix sending infection report to dashboard.stryker-mutator.io

### PR DESCRIPTION
**Pull request by devanych**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

When sending the report, an error occurs due to non-UTF-8 characters that are used in tests.
Probably because of this, will have to abandon the HTML report in this package.

### CODE REVIEW

**Comment by vjik** [comment]
Is problem in Inflector or in Stryker?

**Comment by devanych** [comment]
> Is problem in Inflector or in Stryker?

https://github.com/yiisoft/strings/runs/4777997532?check_suite_focus=true#step:8:198

**Comment by vjik** [comment]
https://github.com/infection/infection/issues/1643

**Comment by maks-rafalko** [comment]
Released and (hopefully) fixed on `0.26.1`, please upgrade Infection and try `report` again

**Comment by vjik** [comment]
https://github.com/Roave/infection-static-analysis-plugin/pull/296

**Pull request merged**
